### ISSUE TITLE
Ribbon is not loading after the solution is imported into the system

### ISSUE THREAD

**Issue by AndrewButenko** [AndrewButenko/ABDialogsV2#4]
![image](https://user-images.githubusercontent.com/11496007/195672321-2073e595-236f-4793-a967-d53276d96ccf.png)

**Comment by bwmodular** [comment]
Just letting you know that I've experienced the same issue. Did you find a way round this?

I'm also finding that even if I add a new row using the modern Maker Portal, when I go back to the app I can't actually edit the record - double-clicking on the newly created row does not open the form... weird...

**Comment by AndrewButenko** [comment]
Hello Ben,
I plan to work on this issue. I believe it's something on the Platform Core side of things.
I will keep you posted.
Andrew

**Comment by AndrewButenko** [comment]
Hello Ben,
It seems to be the issue is caused by "RibbonMetadataGeneration" long-running operation. I created the trial version, installed the solution, and experienced exactly the same issue. I had to wait approximately 30 minutes until that operation was completed and ribbon in "Dialog" entity appeared as it has to appear:
![image](https://user-images.githubusercontent.com/11496007/211239982-eca58e38-04be-4a06-b0c6-513783625217.png)

Let me know if it doesn't work for you. I read multiple threads in regards to similar issues and the only "good" way was to open a support ticket with Microsoft so I bet there is nothing wrong with the solution itself - there is something with the dynamics core that's related to the import and publishing of the solution.

Andrew

**Comment by bwmodular** [comment]
Hi Andrew,Thanks for that. I’ll try it again later this morning and let you know…..Best wishes,Ben

**Comment by bwmodular** [comment]
Hi Andrew,
so I refreshed the browser where I did the original install last night (Edge with and Edge profile) and the problem is still there.
I then opened a new private session in Firefox and the icons are there and the form opens.
I then started a new private Edge session and this has also fixed the issue.

So, I think a combination of patience and cache clearing fixes the issue. As you say, it's a problem with the platform not with your solution.
Thanks for sharing this solution with us - I look forward to exploring its capabilities today.
Ben

**Comment by bwmodular** [comment]
Minor update. The ribbon and form still not behaving in an Edge _profile_ after the above. Clearing the browser history in that Edge profile and restarting has fixed things there too...

**Comment by AndrewButenko** [comment]
Closing this issue cause it's not the solution's issue but the issue of the application core. I believe the issue is related to the fact that I modify the "global" ribbon - the ribbon that is used on all the forms that exactly causes the issue to appear.

**Comment by AndrewButenko** [comment]
@bwmodular and obviously I would love to hear your feedback in regard to the solution overall.

**Comment by bwmodular** [comment]
> 

Any chance you could post even a basic javascript snippet in the docs to demonstrate how to call the dialog using js? I know the docs are a work in progress but a snippet might help to get people going?

**Comment by AndrewButenko** [comment]
Ok. I will work on it since the demand appeared. But you can test your new dialog from the Dialog Selector - https://github.com/AndrewButenko/ABDialogsV2/wiki/4.-Calling-dialog-from-the-record-form

**Comment by bwmodular** [comment]
Ah, great - if there's already a way to preview dialogues, that's all I need for now. Thanks again.
